// <auto-generated />
namespace Ecommerce.CtrlX.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productsError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productsError));
        
        string IMigrationMetadata.Id
        {
            get { return "202005290117470_productsError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
